language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pep8
  - pip install coveralls
before_script:
  - cp registero/default_settings.py registero/settings.py
script:
  - pep8 news contest_registration registero/  --exclude=migrations,default_settings.py --ignore=E128
  - python manage.py makemigrations
  - python manage.py syncdb
  - coverage run --source=news,contest_registration ./manage.py test
after_success:
  coveralls
