# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import team_registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(help_text='Nazwa szko\u0142y/uczelni wy\u017cszej z kt\xf3rej pochodz\u0105 dru\u017cyny danego trenera.', max_length=255, verbose_name='Nazwa o\u015brodka')),
                ('institute_type', models.CharField(choices=[(b'u', 'Szko\u0142a wy\u017csza'), (b's', 'Szko\u0142a \u015brednia')], max_length=1, verbose_name='Typ o\u015brodka')),
                ('accomodation_required', models.BooleanField(default=False, help_text='Zaznacz je\u017celi dru\u017cyny s\u0105 przyjezdne i wymagaj\u0105 znalezienia miejsca do spania.', verbose_name='Wymagane zakwaterowanie')),
                ('institute_address', models.TextField(blank=True, help_text='Adres wcze\u015bniej podanej szko\u0142y/uczelni.', null=True, verbose_name='Adres o\u015brodka')),
                ('institute_nip', models.CharField(blank=True, help_text='Numer NIP o\u015brodka wykorzystywany na fakturze za zakwaterowanie.', max_length=10, null=True, verbose_name='Numer NIP o\u015brodka')),
                ('comment', models.TextField(blank=True, help_text='Podziel si\u0119 wszelkimi dodatkowymi informacjami na temat dru\u017cyn.', null=True, verbose_name='Komentarz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil trenera',
                'verbose_name_plural': 'Profile trener\xf3w',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Imi\u0119')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('shirt_size', models.CharField(choices=[(b'XS', 'Bardzo ma\u0142a (XS)'), (b'S', 'Ma\u0142a (S)'), (b'M', '\u015arednia (M)'), (b'L', 'Du\u017ca (L)'), (b'XL', 'Bardzo du\u017ca (XL)')], default=b'M', max_length=2, verbose_name='Wielko\u015b\u0107 koszulki')),
            ],
            options={
                'verbose_name': 'Uczestnik',
                'verbose_name_plural': 'Uczestnicy',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Kolejno\u015b\u0107')),
                ('approved', models.BooleanField(default=False, help_text='Zaznacz je\u017celi dru\u017cyna ma by\u0107 zaakceptowana na turniej.', verbose_name='Zaakceptowana')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Trener')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Dru\u017cyna',
                'verbose_name_plural': 'Dru\u017cyny',
            },
        ),
        migrations.CreateModel(
            name='TeamRegistrationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='If set to false the team registration is disabled, now matter the start and end settings below.', verbose_name='Rejestracja dru\u017cyn aktywna')),
                ('registration_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pocz\u0105tek rejestracji dru\u017cyn')),
                ('registration_freeze', models.DateTimeField(default=team_registration.models.twenty_five_days_from_now, help_text='After team freeze the team participants cannot be changed, but the teams can still be reordered.', verbose_name='Czas zamro\u017cenia rejestracji dru\u017cyn')),
                ('registration_end', models.DateTimeField(default=team_registration.models.thirty_days_from_now, verbose_name='Koniec rejestracji dru\u017cyn')),
            ],
            options={
                'verbose_name': 'Konfiguracja rejestracji dru\u017cyn',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='team_registration.Team', verbose_name='Dru\u017cyna'),
        ),
    ]
